apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.appName | default('my-app') }}
  annotations:
    backstage.io/kubernetes-id: ${{ parameters.appName | default('my-app') }}
    backstage.io/kubernetes-namespace: workloads
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/kyverno: enabled
spec:
  type: service
  lifecycle: experimental
  owner: group:default/devops
  system: workloads
