apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-golden-path
  description: A secure crossplane workload
  annotations:
    backstage.io/kubernetes-id: test-golden-path
    backstage.io/kubernetes-namespace: workloads
    janus-idp.io/kyverno: enabled
spec:
  type: service
  lifecycle: experimental
  owner: development
