apiVersion: example.crossplane.io/v1alpha1
kind: LocalDeployment
metadata:
  name: test-golden-path
  namespace: workloads
  labels:
    backstage.io/kubernetes-id: test-golden-path
spec:
  parameters:
    image: nginx:1.27-alpine
    hostname: test-golden.local
    port: 80
    replicas: 1
