apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-golden-path2
  description: A secure crossplane workload
  annotations:
    backstage.io/kubernetes-id: test-golden-path2
    backstage.io/kubernetes-namespace: workloads
    kyverno.io/namespace: workloads
    kyverno.io/kind: Deployment,Pod
    kyverno.io/resource-name: test-golden-path2
spec:
  type: service
  lifecycle: experimental
  owner: development
  dependsOn:
    - resource:default/kubernetes-cluster
