apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-final-app
  description: A secure crossplane workload
  annotations:
    backstage.io/kubernetes-id: demo-final-app
    backstage.io/kubernetes-namespace: workloads
    kyverno.io/resource-name: demo-final-app
spec:
  type: service
  lifecycle: experimental
  owner: development
